import type {
  BLOrderItemResponse,
  BLOrderResponse,
} from "../../marketplaces/bricklink/orders/schema";
import type {
  BOOrderItemsResponse,
  BOOrderResponse,
} from "../../marketplaces/brickowl/orders/schema";

export const bricklinkOrderFixture: BLOrderResponse = {
  order_id: "1234567",
  resource_id: 9876543,
  date_ordered: "2024-10-12T14:32:10.000Z",
  date_status_changed: "2024-10-13T09:00:00.000Z",
  seller_name: "Example Seller",
  store_name: "Example Seller",
  buyer_name: "Ada Lovelace",
  buyer_email: "ada.lovelace@example.com",
  buyer_order_count: 5,
  require_insurance: false,
  status: "PAID",
  is_invoiced: true,
  is_filed: false,
  drive_thru_sent: true,
  salesTax_collected_by_bl: false,
  remarks: "Please ship ASAP",
  total_count: 6,
  unique_count: 3,
  total_weight: "1.2",
  payment: {
    method: "PayPal",
    currency_code: "USD",
    date_paid: "2024-10-13T08:30:00.000Z",
    status: "Completed",
  },
  shipping: {
    method: "USPS Priority",
    method_id: 12,
    tracking_no: "TRACK123456789",
    tracking_link: "https://tools.usps.com/go/TrackConfirmAction?q=TRACK123456789",
    date_shipped: "2024-10-14T16:45:00.000Z",
    address: {
      name: {
        full: "Ada Lovelace",
        first: "Ada",
        last: "Lovelace",
      },
      full: "Ada Lovelace\n123 Example St\nCityville, ST 12345",
      address1: "123 Example St",
      address2: "Suite 100",
      country_code: "US",
      city: "Cityville",
      state: "ST",
      postal_code: "12345",
      phone_number: "+1-555-0100",
    },
  },
  cost: {
    currency_code: "USD",
    subtotal: "18.00",
    grand_total: "25.50",
    salesTax_collected_by_BL: "0.00",
    final_total: "25.50",
    etc1: "0.00",
    etc2: "0.00",
    insurance: "0.00",
    shipping: "7.50",
    credit: "0.00",
    coupon: "0.00",
    vat_rate: "0",
    vat_amount: "0",
  },
  disp_cost: {
    currency_code: "USD",
    subtotal: "18.00",
    grand_total: "25.50",
    insurance: "0.00",
    shipping: "7.50",
    credit: "0.00",
    coupon: "0.00",
  },
};

export const bricklinkOrderItemsFixture: BLOrderItemResponse[][] = [
  [
    {
      inventory_id: 101,
      item: {
        no: "3001",
        name: "Brick 2 x 4",
        type: "PART",
        category_id: 11,
      },
      color_id: 0,
      color_name: "Black",
      quantity: 4,
      new_or_used: "N",
      completeness: "C",
      unit_price: "0.35",
      unit_price_final: "0.30",
      currency_code: "USD",
      remarks: "BIN-A1",
      description: "Black Brick 2 x 4",
      weight: "12.5",
    },
    {
      inventory_id: 102,
      item: {
        no: "3004",
        name: "Brick 1 x 2",
        type: "PART",
        category_id: 11,
      },
      color_id: 1,
      color_name: "Blue",
      quantity: 2,
      new_or_used: "U",
      completeness: "B",
      unit_price: "0.25",
      unit_price_final: "0.20",
      currency_code: "USD",
      remarks: "BIN-B2",
      description: "Blue Brick 1 x 2",
      weight: "5.0",
    },
  ],
  [
    {
      inventory_id: 103,
      item: {
        no: "3020",
        name: "Plate 2 x 4",
        type: "PART",
        category_id: 12,
      },
      color_id: 4,
      color_name: "Red",
      quantity: 3,
      new_or_used: "N",
      completeness: "S",
      unit_price: "0.40",
      unit_price_final: "0.38",
      currency_code: "USD",
      remarks: "BIN-C3",
      description: "Red Plate 2 x 4",
      weight: "7.5",
    },
  ],
];

export const brickowlOrderFixture: BOOrderResponse = {
  order_id: "BO-12345",
  id: "BO-12345",
  order_number: "778899",
  store_id: "55",
  status: "3",
  status_id: "3",
  status_text: "Processing",
  created: "1696243200",
  created_at: "2023-10-02T10:00:00Z",
  order_time: 1696243200,
  updated: "2023-10-03T12:15:00Z",
  updated_at: "2023-10-03T12:15:00Z",
  buyer: {
    username: "brickfan",
    name: "Brick Fan",
    email: "fan@example.com",
    order_count: "7",
  },
  customer: {
    username: "brickfan",
    loyalty_level: "gold",
  },
  buyer_name: "Brick Fan",
  buyer_email: "fan@example.com",
  buyer_order_count: "7",
  seller_name: "Brick Seller",
  store_name: "Brick Vendor",
  store: {
    name: "Brick Vendor",
    country: "US",
  },
  payment: {
    method: "Stripe",
    currency: "USD",
    status: "received",
    total: "45.00",
    subtotal: "40.00",
  },
  shipping: {
    method: "USPS Priority",
    method_id: "24",
    tracking_id: "1Z999",
    tracking_url: "https://tools.usps.com/go/TrackConfirmAction?q=1Z999",
    address: {
      name: {
        full: "Brick Fan",
      },
      line1: "456 Example Ave",
      line2: "Unit 9",
      city: "Bricktown",
      state: "CA",
      postal_code: "94105",
      country: "USA",
      country_code: "US",
      phone: "+1-555-0200",
    },
  },
  note: "Leave at front door",
  subtotal: "40.00",
  items_total: "40.00",
  total: "45.00",
  grand_total: "45.00",
  final_total: "45.00",
  tax_total: "2.50",
  shipping_total: "5.00",
  insurance_total: "0.00",
  discount_total: "1.00",
  credit_total: "0.50",
  coupon_total: "0.25",
  total_items: "5",
  total_quantity: "5",
  item_count: "3",
  unique_items: "3",
  unique_count: "3",
  total_weight: "250",
};

export const brickowlOrderItemsFixture: BOOrderItemsResponse = [
  {
    order_item_id: "item-1",
    lot_id: "lot-1",
    order_id: "BO-12345",
    boid: "BO-ITEM-1",
    item_no: "3001",
    external_id: "BRICK-3001",
    name: "Brick 2 x 4",
    type: "Part",
    category_id: "11",
    color_id: "1",
    color_name: "Blue",
    quantity: "2",
    qty: "2",
    total_quantity: "2",
    price: "0.35",
    unit_price: "0.35",
    final_price: "0.30",
    currency: "USD",
    condition: "New",
    completeness: "Complete",
    note: "Top seller",
    remarks: "Bin-1",
    description: "Blue Brick 2 x 4",
    weight: "6.5",
    location: "A1",
  },
  {
    order_item_id: "item-2",
    lot_id: "lot-2",
    order_id: "BO-12345",
    boid: "BO-ITEM-2",
    item_no: "3004",
    name: "Brick 1 x 2",
    type: "Part",
    category_id: "11",
    color_id: "4",
    color_name: "Red",
    quantity: "1",
    price: "0.25",
    unit_price: "0.25",
    final_price: "0.25",
    currency: "USD",
    condition: "u",
    completeness: "Partial",
    description: "Red Brick 1 x 2",
    weight: "2.5",
    bin: "B2",
  },
  {
    order_item_id: "item-3",
    lot_id: "lot-3",
    order_id: "BO-12345",
    boid: "BO-ITEM-3",
    item_no: "3020",
    name: "Plate 2 x 4",
    type: "Part",
    category_id: "12",
    color_id: "85",
    color_name: "Dark Bluish Gray",
    qty: "3",
    total_quantity: "3",
    price: "0.40",
    final_price: "0.36",
    currency: "USD",
    condition: "USED",
    completeness: "Complete",
    remarks: "Shelf C3",
    description: "Dark Bluish Gray Plate 2 x 4",
    weight: "7.5",
  },
];
